"""Constants for color utilities."""

COLORGRAM_PALETTE_COLORS = 5
FALLBACK_PALETTE_ATTEMPTS = 5
NEAR_BLACK_THRESHOLD = 0.1
SATURATION_BOOST_THRESHOLD = 0.4

RGB_HEX_LENGTH = 6
RGB_BYTE_MAX = 255
PERCENT_MAX = 100

MIN_VALUE_PERCENT = 1.0
BLACK_DISTANCE_GAMMA = 2.5

BLACK = (0, 0, 0)
