"""Constants for color utilities."""

FALLBACK_PALETTE_ATTEMPTS = 5

RGB_HEX_LENGTH = 6
RGB_BYTE_MAX = 255
PERCENT_MAX = 100

DEFAULT_HUE_MAX = 360
DEFAULT_SATURATION_MAX = RGB_BYTE_MAX
DEFAULT_VALUE_MAX = RGB_BYTE_MAX
DEFAULT_MIN_VALUE_PERCENT = 1.0
DEFAULT_BRIGHTNESS_SCALE = 0.25

RED_LUMINANCE_WEIGHT = 0.2126
GREEN_LUMINANCE_WEIGHT = 0.7152
BLUE_LUMINANCE_WEIGHT = 0.0722
